### ISSUE TITLE
[Enhancement] Display own device under 'discover hosts' result for port scanning

### ISSUE THREAD

**Issue by Wolfram-Wolf** [aaronjwood/PortAuthority#101]

**Comment by timofonic** [comment]
@aaronjwood Any news about this?

**Comment by aaronjwood** [comment]
Sorry, been busy with a new job lately. Is there a certain reason you want the device itself to be in the list? All the info about the device should be up top. If someone port scans their own device it usually produces inaccurate results.

**Comment by Wolfram-Wolf** [comment]
I reasoned that it'd be more logical. However, I do get the "port-scan own device" part...
