### ISSUE TITLE
Unable to download OUI database

### ISSUE THREAD

**Issue by slackhead** [aaronjwood/PortAuthority#105]
I noticed that all vendors were showing as unknown. I saw the connection going out to wireshark.org so I opened their site in a browser and was faced by a captcha. It seems that this is blocking the database from downloading.

**Comment by aaronjwood** [comment]
Hmm are you on a corporate network or any kind of network with a transparent proxy? I'm not able to reproduce your issue.

**Comment by arthur4ik** [comment]
I'm facing the same issue "Vendor not in database".
Fresh installation of v2.2.8

**Comment by aaronjwood** [comment]
Are you guys still hitting this? Does it only happen on a specific network that you use or does it happen anywhere?

**Comment by arthur4ik** [comment]
seems to be fixed

**Comment by zentech** [comment]
I saw it.. I thought maybe didn't find the Mac vendor
