### ISSUE TITLE
DNS lookup always "No records found." on Android 9

### ISSUE THREAD

**Issue by wesinator** [aaronjwood/PortAuthority#107]
v2.2.8
Android 9.0
Private DNS is enabled

DNS lookups always show "No records found."
`A` record for www.google.com

Disabling Private DNS did not fix it

**Comment by aaronjwood** [comment]
Thanks, I can reproduce this on my Android 9 device as well. I'll take a look at what's going on.

**Comment by aaronjwood** [comment]
Related to the swath of Android 8+ changes https://github.com/dnsjava/dnsjava/issues/6

**Comment by aaronjwood** [comment]
This is supposedly fixed but it hasn't been released yet https://github.com/dnsjava/dnsjava/pull/82

**Comment by op3** [comment]
A new version of dnsjava has been released, see https://github.com/dnsjava/dnsjava/releases/tag/v3.0.0

**Comment by aaronjwood** [comment]
Fixed with https://github.com/aaronjwood/PortAuthority/commit/14a14a8f43c4a697cc50177afeca92fb0021a5fb
