### ISSUE TITLE
<unknown ssid> on android 8.1 sdk 26

### ISSUE THREAD

**Issue by zentech** [aaronjwood/PortAuthority#108]
after installing some updates on my phone. getssid stop working. application no longer detects ssid of wireless network. I believe this is due to new security update on api / sdk. ssid reveals phone location. need fixing!!

**Comment by aaronjwood** [comment]
Fixed with https://github.com/aaronjwood/PortAuthority/commit/43bc9f207e0ccb40b085fd7080b98533ea7a4181

Will be pushing out a new release with this soon...
