### ISSUE TITLE
Unable to access device ARP table

### ISSUE THREAD

**Issue by hexaholic** [aaronjwood/PortAuthority#109]
Hi Aaron,

Every time I try to discover hosts, a toast popup saying "Unable to access device ARP table" appears.

I updated my device to Android 10 recently, that might be the root cause.

Using version 2.2.8 from F-Droid.

**Comment by aaronjwood** [comment]
Unfortunately Android 10 is the culprit https://developer.android.com/about/versions/10/privacy/changes#proc-net-filesystem

**Comment by aaronjwood** [comment]
Fixed with https://github.com/aaronjwood/PortAuthority/commit/e1bcdaa25dda9529cc8d567817e83279967cabb1

Will be rolling out a new release with this soon...

**Comment by hexaholic** [comment]
Thank you very much for taking care of this issue.
I see that v2.2.10 has been released. Will this version be available on F-Droid?

**Comment by aaronjwood** [comment]
No problem! F-Droid should have automatically picked this up. I'm surprised it hasn't by now. If you don't see it on there in the next few days let me know.

**Comment by atomicwrites** [comment]
I just found your app on fdroid and it's still on 2.2.8. I've installed the version on GitHub for now.

**Comment by aaronjwood** [comment]
Thanks, I'll reopen this https://github.com/aaronjwood/PortAuthority/issues/113 until the new build comes out
