### ISSUE TITLE
f-droid cannot compile the latest version 2.2.10

### ISSUE THREAD

**Issue by OmlineEditor** [aaronjwood/PortAuthority#113]
f-droid cannot compile the latest version. 
we need help in solving the problem. See where the problem is and solve it.
https://f-droid.org/wiki/page/com.aaronjwood.portauthority/lastbuild_56

**Comment by aaronjwood** [comment]
It's right that those branches/tags don't exist. I've never used that tag format. If you look at all my other releases the tags are regular semver like vx.x.x. Any ideas why F-Droid is trying to use this new format for checking out?

**Comment by OmlineEditor** [comment]
this may be a bug. you have a tag update in your settings. in the settings, there is no word " - free"
https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.aaronjwood.portauthority.yml

open the ticket and ask what the problem is:
https://gitlab.com/fdroid/fdroiddata/issues

**Comment by aaronjwood** [comment]
Should be fixed now:
https://gitlab.com/fdroid/fdroiddata/issues/1935#note_281789734
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6292

**Comment by OmlineEditor** [comment]
there is no new version on the site. please change the version to make it 2.2.11 then the program will compile it.

**Comment by aaronjwood** [comment]
Latest release is here https://github.com/aaronjwood/PortAuthority/releases/tag/v2.2.12
