### ISSUE TITLE
Add pt_BR translation, pls

### ISSUE THREAD

**Issue by aevw** [aaronjwood/PortAuthority#114]
Hello PA devs, 

I translated strings to [pt_BR](https://github.com/aevw/RD-pt_BR/blob/master/PA-strings.xml)  to make it easier for local users.

Thanks

**Comment by aaronjwood** [comment]
Thanks! Could you make a PR with these changes?

**Comment by aevw** [comment]
For now I can't but feel free to implement it however you want with ou without any modifications.

Thanks

**Comment by aaronjwood** [comment]
https://github.com/aaronjwood/PortAuthority/pull/116
