### ISSUE TITLE
Rationalize Vendor not in database case scenarios

### ISSUE THREAD

**Issue by dantecpu** [aaronjwood/PortAuthority#117]
If we consider this article: https://superuser.com/questions/1444576/up-to-date-oui-database-online we find an interesting referece to improve the OUI parser:

* If a MAC address does not match any entry in the official IEEE registry.

_Actually what it does now..._

**And this scenario that isn't covered by the parser:**

* **If the 2nd digit is 2/6/A/E, it is a private (locally administrated) address.** It doesn't correspond to any OUI prefix – it's the MAC equivalent of 192.168.x IP addresses.

The address might still be based on the manufacturer's OUI, or it might be completely random (generated on the spot).

Many phones and laptops nowadays generate random MAC addresses for Wi-Fi connections.

* **If the 2nd digit is odd (1/3/5/7/9/B/D/F), it is a group (multicast) address.**

 It doesn't belong to an individual device, but it may show up as a destination address in frames.

Finally, it's not impossible that a manufacturer might cheap out on OUI registration and just take a random prefix without getting any IEEE authorization.

I would like to propose to implement those two highlighted rules to modify the parser behavior in the case a Private address or a multicast address is provided.

**Comment by aaronjwood** [comment]
Sounds good, what would you like to see when this case occurs? Some indicator that it may be randomly generated or that it's for multicast?

**Comment by dantecpu** [comment]
Yes, I would appreciate an indicator for it that states that is either a private address or multicast, as I understood, such private devices will be never added to the OUI database for their nature of being private addresses. 

Like for example an address starting like this: 

![port_authority](https://user-images.githubusercontent.com/7214961/93061542-fe84a800-f673-11ea-9ffc-983d8de2b728.jpg)

**Comment by aaronjwood** [comment]
Will be in the next release https://github.com/aaronjwood/PortAuthority/commit/3ca24ddb9a50fd6c5f7097ab709709f749d76152

**Comment by dantecpu** [comment]
I like the result, working fine here, thank you!
![image](https://user-images.githubusercontent.com/7214961/93130003-26a2f400-f6d2-11ea-9a60-e3e6100a6581.png)

**Comment by aaronjwood** [comment]
Awesome! Thanks for trying it out too :)
