### ISSUE TITLE
Internet need to scan the LAN.

### ISSUE THREAD

**Issue by molitona** [aaronjwood/PortAuthority#120]
Hi, I wonder why when I cut Internet access to the app, the LAN scan doesn't work.
It seems that the app need Internet to scan a LAN, but why ?
Thanks.

**Comment by aaronjwood** [comment]
Hmm, that shouldn't be. I'll check into this. Did you just cut access via permissions or with something else?

**Comment by molitona** [comment]
Via settings.

**Comment by molitona** [comment]
Hi, have you tested It ?

**Comment by aaronjwood** [comment]
Not yet, will need a bit of time.

**Comment by aaronjwood** [comment]
I haven't been able to repro this. I went into my phone's settings and turned off mobile data entirely and everything still worked, but that's not a very good test. I don't have an option anywhere in my settings to disable WAN access for a specific app. 

What OS version do you have? And how exactly are you cutting internet access?

**Comment by molitona** [comment]
I'm running Android 7.1.2.

I cut WIFI, Mobile and VPN access (see picture) and the scan goes very fast about half a second displaying only the gateway host.

**Comment by aaronjwood** [comment]
I think you forgot to upload the picture :)

I heard they removed some of those settings in Oreo which is maybe why I don't see the same options as you. Let me do some research and see what those settings actually did underneath on older versions of Android.

**Comment by molitona** [comment]
![Uploading e6468a37-9038-48c3-8bf9-f36837694508.png…]()

**Comment by molitona** [comment]
![e6468a37-9038-48c3-8bf9-f36837694508](https://user-images.githubusercontent.com/35532337/103467551-129a0580-4d48-11eb-96ac-700788de82c5.png)

**Comment by aaronjwood** [comment]
Are you running LineageOS by chance?

**Comment by molitona** [comment]
Yeah, indeed. Is that the problem ?

**Comment by aaronjwood** [comment]
It looks specific to LineageOS https://review.lineageos.org/c/LineageOS/android_packages_apps_Settings/+/259455/

I would need to scan through their codebase for their Android 7 release to see what it's exactly doing in the OS. My educated guess is that these settings are preventing "data access" which doesn't differentiate between LAN or WAN. In your screen shot above they even say "prevent any use of..." which should technically mean any data flowing in/out anywhere.

**Comment by molitona** [comment]
Fine, hope you can come with a solution :)

**Comment by aaronjwood** [comment]
Well if their setting is restricting any data (LAN or WAN) then scans won't work when you turn this setting on. The app needs to send/receive data on the LAN for it to work correctly.

**Comment by molitona** [comment]
I've tested Netguard now with the same result.

**Comment by aaronjwood** [comment]
I'm not familiar with Netguard, what is that doing for you? Is it cutting all data access?

**Comment by molitona** [comment]
Yep, using iptables, but It seems that It cuts LAN access as well.

**Comment by aaronjwood** [comment]
If both of these scenarios are disabling connectivity to the LAN then it's not something I can support. You need LAN access to scan things so you'll need to find a way to only disable WAN access in order for things to work.

**Comment by molitona** [comment]
Ok thanks for your help, I will do so :)
