### ISSUE TITLE
google force targeted SDK to 30 | Host scan do not work on Android 11

### ISSUE THREAD

**Issue by goldfish07** [aaronjwood/PortAuthority#129]
host scan is not working in android 11, will this app ever get updated in play store ?

**Comment by goldfish07** [comment]
#125

**Comment by goldfish07** [comment]
https://issuetracker.google.com/issues/130103885

**Comment by aaronjwood** [comment]
Ugh, I can understand that they want to tighten Android more and more but it certainly makes writing these kinds of apps a pain. We'll need a fallback now for when the ARP table is not accessible...

**Comment by aaronjwood** [comment]
Fixes for this should be rolling out today.
