### ISSUE TITLE
Difference in detection android 9 vs 11

### ISSUE THREAD

**Issue by Jacksack2000** [aaronjwood/PortAuthority#133]
Wanted to start a second issue independently from the "no or just a small portion of wifi devices were detected".

I installed your app on an android 9 as well as on an android 11.

In case of the android 9 my router is detected. So far so good. 

In case of the android 11 device my router is detected twice! First, normally as it should with an ipv4 and the routers name,
but the second entry/listing is just showing the routers ipv6, thus suggesting it is a different device.

Any idea what's going on?

**Comment by aaronjwood** [comment]
It sounds like one of your devices has ipv6 capability while the other one does not (just a guess without seeing any data). The app won't consolidate devices as of today, if it finds something with multiple IPs it'll show up multiple times.
