### ISSUE TITLE
Android 13 - not working 

### ISSUE THREAD

**Issue by markusschloesser** [aaronjwood/PortAuthority#147]
When trying to discover hosts, shows "unable to fetch ARP entries"
Pixel 6 pro, android 13, official
App Version 2.4.1 installed from f-droid 
(tried Ning, which works, but I much prefer port authority)

**Comment by derflasher** [comment]
Can confirm on Pixel 4 with Android 13.

**Comment by aaronjwood** [comment]
Fixes for this should be rolling out today.

**Comment by markusschloesser** [comment]
fantastic, thank you! 👍
