### ISSUE TITLE
Crash on scanning host address (192.168.1.1)

### ISSUE THREAD

**Issue by Draako** [aaronjwood/PortAuthority#15]
The app crashes on scanning 192.168.1.1 OpenWRT router address.

**Comment by aaronjwood** [comment]
Thanks for reporting this. It's something I'm aware of and should be fixed within the next few versions. I've already started working on the fix in a separate branch.

**Comment by aaronjwood** [comment]
Going to close this as I'm pushing out a new version right now that should resolve this issue.
