### ISSUE TITLE
F-Droid build failed for V2.4.3

### ISSUE THREAD

**Issue by derflasher** [aaronjwood/PortAuthority#150]
Dear developer,

Thank you for the app.
Unfortunately the build failed on F-Droid. May you make it in work?

Thank you so much!

**Comment by derflasher** [comment]
But the build still fails...

**Comment by aaronjwood** [comment]
Yeah, will get it fixed up soon.

**Comment by aaronjwood** [comment]
The build is now working so likely they just haven't gotten around to publishing the release yet https://monitor.f-droid.org/builds/log/com.aaronjwood.portauthority/65#site-footer
