### ISSUE TITLE
Discovered Hosts

### ISSUE THREAD

**Issue by apm1007** [aaronjwood/PortAuthority#17]
How about ascending or descending hosts? Would be great to get Hostname directly in the discover overview. How about opening port eighty directly to browser? Im missing this feature.

**Comment by aaronjwood** [comment]
Most of these things are on my list :)

**Comment by aaronjwood** [comment]
The host name detection should be more accurate going forward as I'm using both DNS and NetBIOS to get whatever I can. Ports corresponding to web services can be opened to the browser now as well.
87a8465a8079dcf05a57225747ca4fadd0ba384e

Expect to see this stuff in the 1.6 release

**Comment by aaronjwood** [comment]
Just rolled out the 1.6 release. Let me know what you think! I haven't implemented the sorting of hosts yet, but everything else should be there.

**Comment by aaronjwood** [comment]
Will open a new issue for the sorting request.
