### ISSUE TITLE
Line breaks 

### ISSUE THREAD

**Issue by lightonflux** [aaronjwood/PortAuthority#18]
When you have longer lines the spacing gets ugly.

Especially the 

     Hostnam
     e

And for the name it would be handy if the app breaks at - and .  In this case after "static".

![linebreaks](https://cloud.githubusercontent.com/assets/1377943/7556091/73686802-f763-11e4-9f45-a2c6f3dc1fc0.png)

**Comment by aaronjwood** [comment]
This is fixed in the upcoming 1.5.1 release. As always, thanks for the feedback!

**Comment by lightonflux** [comment]
Hurray scrolling text!

But now i have this nice glitch with the separator and the MAC address. 


![screenshot_2015-06-21-16-22-36](https://cloud.githubusercontent.com/assets/1377943/8272093/899360fc-1836-11e5-8933-68bc855b043d.png)

**Comment by aaronjwood** [comment]
Gah, I should have caught this beforehand. Dumb mistake on my part, should be fixed now. Pushing out an update right now.
