### ISSUE TITLE
port-range 1.5.2

### ISSUE THREAD

**Issue by ltz44** [aaronjwood/PortAuthority#20]
in the file HostActivity in line 159 "if((startPort - stopPort >= 0)) {"

 should be a "<=" because stopPort must be greater than startPort.
btw nice work

**Comment by aaronjwood** [comment]
Actually I need the value to be greater than or equal to 0. Let's say the user picks port 20 as the start port and port 100 as the end port. 20 - 50 = -30 which satisfies the conditional. If the user picks 100 as the start port and 10 as the end port 100 - 10 = 90 which doesn't satisfy the conditional.

I'm basically protecting against an invalid range. Ranges can be from a start port to an end port and the start port should always be lower than the end port. For example, I don't allow backwards ranges like starting at port 2500 and ending at port 20. It has to be 20 to 2500.

Thanks for the comment! :)
