### ISSUE TITLE
Mac Address not displayed 

### ISSUE THREAD

**Issue by z751** [aaronjwood/PortAuthority#26]
On Android 6, specifically Cyanogenmod 13, the mac address does not display on the main page.

Also, could you please add the MAC vendor to the main device info page?

**Comment by aaronjwood** [comment]
Hi, thanks for the report. Do MAC's show for any of the hosts on your network? What shows up? Something like `[]` or nothing at all?

**Comment by z751** [comment]
The MACs display for the hosts, but on the main section where you scan for hosts, the main device MAC does not display properly.  It just says:  02:00:00:00:00:00.

About the second part, you are correct.  The section where you scan for hosts.

**Comment by aaronjwood** [comment]
Ugh, looks like they prevent getting the local device's MAC now with Android 6+

https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-hardware-id

I'll see if there's anything I can do to work around this without requiring root.

**Comment by z751** [comment]
Thank you.  If there is no work around, would you please consider adding an option to get it using root?

**Comment by aaronjwood** [comment]
Definitely. I believe I should be able to do something about it. Will post back here when I've tested it out. Maybe you could even let me know if it ends up working for you once I have it in place (assuming it tests out okay)

**Comment by aaronjwood** [comment]
I just pushed out a new release containing a fix for this. Could you let me know if it ends up resolving the issue for you? bcbe9c5f119647f141bc64f743221eeaf122a226 is the specific commit that should hopefully work around it.

**Comment by z751** [comment]
I will test it out when the release is pushed to F-Droid.

**Comment by z751** [comment]
I have confirmed that version 1.6.11 fixes this issue with the mac address.  Thank you.

**Comment by z751** [comment]
How is the other request coming along?

**Comment by aaronjwood** [comment]
Awesome, glad to hear that. Will be implementing the MAC vendor piece soon. Just been really busy with life and my full time job :)

**Comment by aaronjwood** [comment]
Okay, the MAC vendor is added to the device info section now. Will be in the next release. See 1a3ba41fd534518ac0038a9aa7d00fdb7c6ccb03
