### ISSUE TITLE
Attach APK to release?

### ISSUE THREAD

**Issue by IzzySoft** [aaronjwood/PortAuthority#28]
Would you consider including the `.apk` file with the `releases/` – for those running their devices "Google-free" and thus having no Play Store access? I'd then even [include it here](https://android.izzysoft.de/repo), so people can use the F-Droid client to stay updated automatically :innocent: Thanks in advance!

**Comment by aaronjwood** [comment]
Sure, I can do that :)

**Comment by IzzySoft** [comment]
Great! Please let me know when you did (currently, there's still no `.apk` available on the latest release), so I will grab it and set up my auto-updater script to check for future releases. Thanks a lot!

**Comment by aaronjwood** [comment]
Okay, should be all set now. I published release notes and binaries going back to `v1.6.0`. Thanks for offering to script it to F-Droid!

**Comment by IzzySoft** [comment]
Thanks a million, Aaron – find it added to my repo, as promised (just updated :)
