### ISSUE TITLE
Force close on Android Lollipop

### ISSUE THREAD

**Issue by sniperle** [aaronjwood/PortAuthority#3]
After starting the app it's closed. Here the logcat:

01-13 09:43:30.138 I/Timeline(14923): Timeline: Activity_launch_request id:com.aaronjwood.portauthority time:44255178
01-13 09:43:30.138 I/ActivityManager(2286): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.aaronjwood.portauthority cmp=com.aaronjwood.portauthority/.activity.MainActivity} from uid 10137 on display 0
01-13 09:43:30.198 I/ActivityManager(2286): Start proc com.aaronjwood.portauthority for activity com.aaronjwood.portauthority/.activity.MainActivity: pid=18992 uid=10332 gids={50332, 9997, 3003} abi=armeabi-v7a
01-13 09:43:30.328 E/AndroidRuntime(18992): Process: com.aaronjwood.portauthority, PID: 18992
01-13 09:43:30.328 E/AndroidRuntime(18992): 	at com.aaronjwood.portauthority.a.a.a(Unknown Source)
01-13 09:43:30.328 E/AndroidRuntime(18992): 	at com.aaronjwood.portauthority.a.a.doInBackground(Unknown Source)
01-13 09:43:30.338 W/ActivityManager(2286):   Force finishing activity com.aaronjwood.portauthority/.activity.MainActivity
01-13 09:43:30.648 I/WindowManager(2286): Screenshot max retries 4 of Token{ed04fb8 ActivityRecord{39cd021b u0 com.aaronjwood.portauthority/.activity.MainActivity t1400 f}} appWin=Window{1ff42e82 u0 com.aaronjwood.portauthority/com.aaronjwood.portauthority.activity.MainActivity} drawState=3
01-13 09:43:30.998 I/Timeline(2286): Timeline: Activity_windows_visible id: ActivityRecord{39cd021b u0 com.aaronjwood.portauthority/.activity.MainActivity t1400 f} time:44256044
01-13 09:43:31.908 I/ActivityManager(2286): Process com.aaronjwood.portauthority (pid 18992) has died
01-13 09:43:32.458 W/PackageManager(2483): Failure retrieving resources for com.aaronjwood.portauthority: Resource ID #0x0

**Comment by aaronjwood** [comment]
What version are you running? This looks very similar to an issue that 1.0.0 had. I fixed that in 1.0.1.
Could you also let me know what device you have and if you had an active wifi connection when this happened?

**Comment by sniperle** [comment]
I was using the F-Droid build version 1.2.2 from today.
My device is a LG G2 (D802) and my WiFi was on and connected.

**Comment by aaronjwood** [comment]
Thanks, I will look into this and get back to you

**Comment by aaronjwood** [comment]
Are you able to browse to this URL from your browser on your device? http://whatismyip.akamai.com/
Preferably on the same network you were on when you experienced the crash.

**Comment by sniperle** [comment]
The Web page at http://whatismyip.akamai.com/ could not be loaded as:

net::ERR_CONNECTION_REFUSED

**Comment by aaronjwood** [comment]
Ah, okay. Interesting. Are you on a corporate network that is blocking that by any chance? I know exactly what the issue is and I'll issue a fix for it ASAP.

**Comment by sniperle** [comment]
This happens on all networks I'm connected to. Tried it from home, university and mobile network.

**Comment by aaronjwood** [comment]
Oh wow, very strange. Are you running a custom rom or do you have any special network filtering software installed on your phone? If you browse to the URL you'll see that all it does is return your WAN IP. Not sure why your phone is blocked it everywhere...

**Comment by sniperle** [comment]
Yes, very strange. I'm using AfWall, but deactivated it while testing, no change. I have CM 12 installed.

**Comment by sniperle** [comment]
Maybe it's because of OpenNIC:  http://www.opennicproject.org/

Have to investigate more.

**Comment by aaronjwood** [comment]
Ah, let me know if you find out if it's the cause. I'll still issue a fix so that the application doesn't crash when things like this happen.

**Comment by aaronjwood** [comment]
I've pushed out a new release (1.2.3) that should fix this issue. Can you confirm when you receive the update?

**Comment by sniperle** [comment]
OK and thank you :-)
