### ISSUE TITLE
Remove "External IP Address" access.

### ISSUE THREAD

**Issue by ghost** [aaronjwood/PortAuthority#30]
I just want a simple port checker app for my network.
I don't want any app to connect outside(Internet) without my permission.

Where does this app connect to check external IP?
Consider removing it or let user to disable it before connection.

**Comment by verycrypt** [comment]
You could tell us about what you connect to, @aaronjwood...

---
public class GetExternalIpAsyncTask extends AsyncTask<Void, Void, String> {
    private static final String EXTERNAL_IP_SERVICE = "https://ipinfo.io/ip";
    private MainAsyncResponse delegate;
---

Added to my DNS BAN list(public) for now.

**Comment by verycrypt** [comment]
Also I'll report this issue to FDroid, starting with this app connect to 3rd party (load remote resouce = TRACKING)

**Comment by aaronjwood** [comment]
Yes, that's where it connects to. I will build in an option to disable external IP fetching along with a few other settings I'm working on.

**Comment by aaronjwood** [comment]
This is done and will be in the next release. See 54800df2f2ab04379d0cc2a31e57b29e5b219468 4b7cc89ba2a6a8e8941930a0c4adb25eddeda8f1 400dfce29f43a42142d7cb85f6176e48e1fca503
