### ISSUE TITLE
"Scan Port Range" - let user to input the port.

### ISSUE THREAD

**Issue by verycrypt** [aaronjwood/PortAuthority#31]
I want to scan my network for security check, but you app makes me hard to specify the port range.

If I need to check port 4567 only, I have to scroll start(1) and end(65535) to 4567,
which takes reaaaaaaaaaaaaaaaaaly looooooooooooong time to swipe my screen.

**Comment by aaronjwood** [comment]
What you can do is tap on the numbers which will pop up a keyboard and let you input whatever you want. No need to scroll around if you don't want to. It's part of Android's [NumberPicker](http://developer.android.com/reference/android/widget/NumberPicker.html)
