### ISSUE TITLE
Display MAC address vendor for the discovered LAN hosts

### ISSUE THREAD

**Issue by ghost** [aaronjwood/PortAuthority#33]
I am sorry to bring this one up again, but it seems that I should have specified in my previous request.  

https://github.com/aaronjwood/PortAuthority/issues/26

Can we please get the MAC address vendor for the: DISCOVERED LAN HOSTS 
in the main device info page?  The reason I ask is that sometimes the host name for some devices does not display on the main page.  Instead it displays the internal IP address of the device.  On a network with many of these said devices, having the MAC vendor will make it easier to know which device it is.

**Comment by aaronjwood** [comment]
https://github.com/aaronjwood/PortAuthority/commit/e84e03238da1519214435de39f606f48d4c57777

Will be making a new release that includes this very soon :)
