### ISSUE TITLE
Screen real-estate on 848×480 device

### ISSUE THREAD

**Issue by nhuillard** [aaronjwood/PortAuthority#34]
I use an old device with 848×480 screen, on which Port Authority (1.7.2 from f-droid) works great, except that the latest release leaves very little space to display the list of devices found. The list of discovered hosts covers 21% of the screen height in portrait mode (and 0% in landscape mode). The status bar + title + "Discover hosts" button have 23%. The "Device info" section uses the rest (56%).
Would it be possible to either disable the "Device info" section when displaying the host list, or using standard font size (title, etc.), or using shorter labels/no line wrap in the "Device info" section ("MAC Address" is uselessly split in 2 lines, horizontal lines take a lot of space, etc.), in order to have a really suable list of devices found ?
TIA

**Comment by aaronjwood** [comment]
Definitely, I'll work on putting something in place for this.

**Comment by aaronjwood** [comment]
I made some changes to the UI in the most recent version to help reduce some of the clutter and redundancy. Can you let me know if it's better for you now?

**Comment by nhuillard** [comment]
Thank you very much for your efforts. I'll have to wait for the release to percolate to f-droid though, because I have no other means to get the app...
I'll try to keep you informed ASAP.

**Comment by aaronjwood** [comment]
You're welcome, it should be here https://f-droid.org/repository/browse/?fdid=com.aaronjwood.portauthority :)

**Comment by nhuillard** [comment]
It's bettter, but still huge... The "Vendor" field is specially disruptive in my case. 

![screenshot_2016-08-24-17-55-19](https://cloud.githubusercontent.com/assets/8738509/17938344/db96866c-6a25-11e6-9738-2456680340c2.png)
![screenshot_2016-08-24-17-55-58](https://cloud.githubusercontent.com/assets/8738509/17938345/db9b38f6-6a25-11e6-80cd-0e430ae5f733.png)

TIA !

**Comment by aaronjwood** [comment]
Thanks for the screenshots. I'll work on a fix this weekend.

**Comment by aaronjwood** [comment]
I just pushed out a new release that should fix these issues in portrait layout (see 9598ae47e6eddb8a7ae69337f9d094e22c2e70c2). A fix for the landscape layout will be coming really soon!

**Comment by aaronjwood** [comment]
Landscape fix is here db9c9896f14b82906f97738fb269536fcc82d49a. Will be making another release for this shortly.

**Comment by aaronjwood** [comment]
Okay, just landed.

**Comment by aaronjwood** [comment]
Did the latest update resolve this for you?

**Comment by nhuillard** [comment]
Sorry for not replying earlier, as I tested as soon as f-droid proposed the update.
I now see 3 items in the discovered hosts list, instead of 2 previously (1 instead of "not usable at all" in portrait mode). That's much better.
Maybe you could make the localhost information part of the sliding list in order to show from 3 items to "all the screen real-estate", when scrolling down.
Thanks for you efforts!

**Comment by aaronjwood** [comment]
No worries, glad to hear it's improved! The overflowing MAC vendor is fixed now too, right?

I'll continue to optimize the layout as I go. Thanks again for the feedback!

**Comment by nhuillard** [comment]
I good screenshot is way better than a dozen words:
![screenshot_2016-09-08-18-34-35](https://cloud.githubusercontent.com/assets/8738509/18358077/b0290304-75f3-11e6-996f-42b1c6f7c95b.png)

**Comment by aaronjwood** [comment]
Awesome! It helps to see what it looks like on your device :)
I'm going to close this issue and reopen another one for adding better support for small screens.
