### ISSUE TITLE
F-Droid version outdated

### ISSUE THREAD

**Issue by z751** [aaronjwood/PortAuthority#35]
The f-droid version seems to be out of date.

It is on 1.7.2

**Comment by aaronjwood** [comment]
I believe @IzzySoft keeps it updated on his repo https://android.izzysoft.de/repo/apk/com.aaronjwood.portauthority.free

**Comment by IzzySoft** [comment]
@aaronjwood believes correctly :) Though I usually avoid duplicating what the "main repo" already has, there are a few exceptions – that is e.g. when F-Droid is completely "out-of-sync". Which seems to be the case here, and as well with e.g. [andFHEM](https://github.com/klassm/andFHEM). Of course, if the dev tells me he doesn't wish so, I'd refrain from it (rare case I guess).

So long story short: Yes, you can expect the updated `.apk` turn up in my repo usually within 24h.

**Comment by aaronjwood** [comment]
@z751 does this work for you?

**Comment by IzzySoft** [comment]
@aaronjwood You might consider adding a related hint to the main `README.md`: as my repo uses the `.apk` you've created, its signature should be compatible to that of the app downloaded from Playstore. Just if someone used the app via the F-Droid main repo, it requires either the app being uninstalled or the appropriate XPosed module (to ignore signature checks) being installed. When in doubt, just try updating straight away: if it works, fine; if it gives an error – well, see above :)

Of course, your choice :smiley_cat:

**Comment by z751** [comment]
I only want the officially supported repos in my F-Droid configuration so I will just wait for the update in the main repo.

**Comment by aaronjwood** [comment]
I'll work on getting this into the official repos.

Thanks for the heads up @IzzySoft!

**Comment by IzzySoft** [comment]
@z751 how do you define "officially supported repos"? Just the main repo and its archive? Only being curious – of course it's your choice what sources you trust (better save than sorry).

@aaronjwood Anytime! As I wrote above: If you get your app back into the "official repo" and want me to kick it out of mine, let me know. If you prefer having it in my repo as well (for an alternative source in case F-Droid goes bu-bu on it again), that's of course fine with me as well. Always glad to help :)

**Comment by aaronjwood** [comment]
@IzzySoft yeah you can definitely keep it in your repo (thanks again for doing that in the first place). I'll additionally get it into the main repo :)

**Comment by IzzySoft** [comment]
@aaronjwood Will do, thanks! As mentioned, it might be a good idea to point out the differences then (F-Droid = different signature, GPlay + Github + mine = same signature). A remark, though: I'm not sure what the F-Droid client will show as the "latest version" then. But those using multiple repositories with their F-Droid client should be aware of that – after all, the same can be said about the Guardian repo and others :)

**Comment by z751** [comment]
@IzzySoft I am reffering to the main repo and the archive as well as the guardian project repo and the corresponding archive repo.

**Comment by IzzySoft** [comment]
@z751 Thanks for clarification! So what makes those "official" for you? That there's an organization behind – or some "security measures" you know of? Or, in other words, what would I need to do to have my repo considered "official"? (Hints: I'm currently working on implementing different APK checks. So hopefully, soon they'll all have a malware check applied as well as their used libraries listed. Might take some time, as this indeed is a one-man-show).

@aaronjwood Sorry for hijacking. Hope you don't mind – and promise not to extend. I just can't let go of this chance :)

**Comment by z751** [comment]
@IzzySoft they are both built-in to the app itself.  Also I know there is a huge team behind it.  Plus when it comes to software I am picky about where I get them.

**Comment by IzzySoft** [comment]
@z751 Understood. Thanks for the feedback! I definitely agree to the last sentence – and of course can understand the first two (which I'll be unable to achieve :innocent:).

**Comment by aaronjwood** [comment]
Don't you want to keep this open until I get it into the official sources?
