### ISSUE TITLE
LAN Host discovery 

### ISSUE THREAD

**Issue by martinum4** [aaronjwood/PortAuthority#37]
Hello,
your app doesn't use the subnet mask to scan all the devices in the subnet, apparently it only scans 255 (gateway + ip subnet of device) hosts.
i got a /20 subnet so it should theoretically ping 4096 devices...

kind regards

Martin

**Comment by aaronjwood** [comment]
There should be functionality built in soon to detect the subnet that the device is on and scan the subnet instead of 1-255 of the last octet. Will keep you posted!

**Comment by aaronjwood** [comment]
Related to #5

**Comment by aaronjwood** [comment]
This will be in the next release (thanks to @thanset for adding this https://github.com/aaronjwood/PortAuthority/pull/58)
