### ISSUE TITLE
the app cannot start

### ISSUE THREAD

**Issue by frazzmark** [aaronjwood/PortAuthority#4]
I'm using galaxy s3 i9300 with CyanogenMod 11 and custom kernel,
The system shows message "app stopped working".

**Comment by aaronjwood** [comment]
Is this all set? Did you close this for a reason?

**Comment by frazzmark** [comment]
Now it works. I don't remember what the problem was actually.

**Comment by aaronjwood** [comment]
Okay if you run into anything again let me know :)
