### ISSUE TITLE
Update the vendor database?

### ISSUE THREAD

**Issue by z751** [aaronjwood/PortAuthority#41]
When was the last time it was updated? A lot of my devices show up as not in the database.

**Comment by aaronjwood** [comment]
It's been a while. There should probably be an auto update thing built in where people can choose when to update it on their own.

**Comment by thanset** [comment]
It would also be nice to be able to label ports on the LAN that users might use for custom services like PLEX.  @aaronjwood We should put this on the feature map in the future I think.

**Comment by aaronjwood** [comment]
@thanset sure, sounds good.

**Comment by z751** [comment]
http://rorist.github.io/android-network-discovery/

That is the app I used to use.  It is open source and the database continues to update though I am not sure where the database is, the source code should reveal that.

**Comment by z751** [comment]
That database is great!

**Comment by aaronjwood** [comment]
@z751 oh nice, I've seen that one a few times. Looks like they use some custom database https://github.com/rorist/android-network-discovery/blob/master/src/info/lamatricexiste/network/Utils/DbUpdate.java#L36

I'll probably use a more official one. I believe this is the one I originally parsed and converted to a local DB http://standards-oui.ieee.org/oui.csv. That one at least is more consistent and much easier to parse than the port data.

**Comment by aaronjwood** [comment]
DB has been updated and will be a part of the next release d81697364a5332129817e3a1c0f0f3995a7659cf
The auto updating of ports/vendors will come later :)

**Comment by PanderMusubi** [comment]
Did you notify IANA about the inconsistencies? Perhaps they will fix it.

**Comment by aaronjwood** [comment]
I haven't but I should. Let me reach out to them.

**Comment by aaronjwood** [comment]
Just sent a note over to them. Will update this thread if/when they respond.

**Comment by Ghost-DW** [comment]
Is there any way of updating the databases (OUI and Ports) myself with a csv or the likes? The integrated fetch shows a file not found error.
