### ISSUE TITLE
Allow sorting of discovered hosts

### ISSUE THREAD

**Issue by aaronjwood** [aaronjwood/PortAuthority#43]
Some users have expressed interest in being able to sort hosts ascending/descending. Related to https://github.com/aaronjwood/PortAuthority/issues/17#issue-73088636

**Comment by thanset** [comment]
@aaronjwood I think a simple drop down menu with sort by (category) would be reasonable, with natural sorting. Do you have anything specific (UI wise) for this feature in your mind?

**Comment by aaronjwood** [comment]
I was thinking of having the same menu drop down like you were saying. The only issue with that is that the action bar is hidden across all of the activities right now as part of the overall UI.

**Comment by aaronjwood** [comment]
https://github.com/aaronjwood/PortAuthority/commit/6f31ec492a976083e814156769d8a7828b3f5be4
