### ISSUE TITLE
Automatic updating of OUI database

### ISSUE THREAD

**Issue by aaronjwood** [aaronjwood/PortAuthority#45]
Build in functionality to allow for users to update the MAC vendor DB themselves so that it doesn't need to be updated in a separate release.

Closely related to #41.

**Comment by z751** [comment]
For privacy reasons can you please make this an opt IN feature or at least provide a toggle off switch/manual update?

**Comment by aaronjwood** [comment]
Yeah, definitely. Are you worried about hitting the internet in general?

**Comment by z751** [comment]
I am not really concerned about it but I am concerned with using non-secure protocols like http.  Will this updater use encryption and or a way to verify that the download has not been compromised?

**Comment by aaronjwood** [comment]
It could be built in. I'd prefer to have it over TLS as well (the endpoint for getting your external IP is over TLS). I'll have to look into the best way to do this. Sadly it looks like IEEE does not have TLS enabled https://standards-oui.ieee.org/oui/oui.csv

**Comment by ryantig** [comment]
Top link below is the same as you would get with your url above (if you did http vs https)
https://standards.ieee.org/develop/regauth/oui/oui.csv
https://standards.ieee.org/develop/regauth/oui28/mam.txt
https://standards.ieee.org/develop/regauth/oui36/oui36.txt
For more see: regauth.standards.ieee.org/standards-ra-web/pub/view.html
Might be able to check the web server for date before pulling the whole thing to see if it is newer.

**Comment by aaronjwood** [comment]
Awesome, thanks @ryantig!

**Comment by Bartoloni** [comment]
for now i've added some "hardcoded" MAC adresses...

        if (mac.equals("00ce39")) vendor += " (Emtec ethernet)";
        if (mac.equals("c6ea1d")) vendor += " (Telecom Italia)";
        if (mac.equals("3ca067")) vendor += " (Liteon TV module)";
        if (mac.equals("d4dccd")) vendor += " (Apple)";
        if (mac.equals("4c74bf")) vendor += " (Apple)";
        if (mac.equals("d8e0e1")) vendor += " (Samsung)";

**Comment by Bartoloni** [comment]
just making a new database (updated 2017)

**Comment by aaronjwood** [comment]
@ryantig it looks like all of these URLs redirect to HTTP in the end :(

**Comment by aaronjwood** [comment]
A snippet from my email to the IEEE:

```
I noticed another issue recently. Trying to download this list https://standards.ieee.org/develop/regauth/oui/oui.csv results in extremely slow transfer speeds. I'm seeing that it takes about ~10 minutes to download that CSV file on a 300/300 up/down fiber internet connection. Sometimes the download just fails altogether and I get an error relating to an unexpected end of the stream. Any ideas why the IEEE server seems to be having trouble serving that file? It's only 2 MB. The other files come across just fine.

Also, the URLs to these lists are HTTPS but they end up redirecting to HTTP in the end. Is it intentional that everything looks as if it's using TLS but isn't really once the redirect is followed? For example, https://standards.ieee.org/develop/regauth/oui/oui.csv redirects to http://standards-oui.ieee.org/oui/oui.csv
```

**Comment by PanderMusubi** [comment]
Confirmed, 3 ~ 6 KB/s download. Takes about 8 minutes. Perhaps setup a cache for this. How often is this URL being updated?

**Comment by aaronjwood** [comment]
Not often, it'll be used for new installs (and when everyone upgrades to the next version) and potentially when people trigger a refresh of OUI data from the settings. You can get an idea of how/when it'll work by following this branch I'm working on https://github.com/aaronjwood/PortAuthority/tree/auto-updates

**Comment by aaronjwood** [comment]
I switched to wiresharks database since they combine all three lists from the IEEE. Plus, it's quick to fetch AND is over TLS ;)

**Comment by aaronjwood** [comment]
No love from the IEEE:

> Since IEEE provides the public listing for assignments that we issue to customers, there are no requirements for our servers to be compatible with other products that utilize the same information or to provide high speed downloads.  Therefore, we are unable to assist you with troubleshooting your specialized product that is using the data that we provide.  IEEE does not authorize the use of the data in this product.

**Comment by aaronjwood** [comment]
This is all set and will be included in the next release.
