### ISSUE TITLE
Netmask sometimes returns 0

### ISSUE THREAD

**Issue by aaronjwood** [aaronjwood/PortAuthority#51]
https://github.com/aaronjwood/PortAuthority/blob/development/app/src/main/java/com/aaronjwood/portauthority/network/Wireless.java#L156

https://code.google.com/p/android/issues/detail?id=82477

**Comment by thanset** [comment]
This is fixed in my latest pull request...once fixed this will be solved. @aaronjwood you can assign this to me.

**Comment by aaronjwood** [comment]
Looks like this is fixed now with your patch.
