### ISSUE TITLE
Question about network speed

### ISSUE THREAD

**Issue by ghost** [aaronjwood/PortAuthority#57]
Is it possible to build a feature that will test your download and upload speed?

**Comment by aaronjwood** [comment]
Are you looking for this to be LAN or WAN based?

**Comment by VREMSoftwareDevelopment** [comment]
[https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/issues/59 (Same Question)](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/issues/59)

There is an application in GitHub that does the speed test: [https://github.com/caarmen/network-monitor](https://github.com/caarmen/network-monitor)

**Comment by z751** [comment]
What exactly would be the difference?  I am looking for a way that is like speedtest.net.  There is no such app like that currently in the F-Droid repo.

**Comment by aaronjwood** [comment]
What about the app that @VREMSoftwareDevelopment mentioned? That looks like it has a speed test feature built in.

**Comment by z751** [comment]
I am not a fan of that app for several reasons.
