### ISSUE TITLE
App name "PortAuthority" feedback

### ISSUE THREAD

**Issue by user8446** [aaronjwood/PortAuthority#68]
First, I'm switching to the donate version. Thank you for the great app!
Just my personal observation: I was looking for a LAN scanner when I accidentally came across "PortAuthority - Port Scanner". Because of the name, it would appear that this is just a port scanner at first glance. I'm glad I found it, because it has other features I was also looking for. A name improvement may bring in many more users that accidentally overlooked it.

**Comment by aaronjwood** [comment]
Thanks for the feedback and your support! I'm glad to hear that you found the app useful :) I'll definitely consider a name change for the app. Never really thought to push the LAN scanning piece of it, I always thought people would be more interested in the port scanning part!

**Comment by aaronjwood** [comment]
I'll have to think on this one, the Play store only allows 30 characters max for the title and I'm using 29 of them.

**Comment by Tony-il-Capo** [comment]
IMO the name is appropriate and good enough.

**Comment by aaronjwood** [comment]
Google recently upped the character limit from 30 to 50 so this is now possible!
