### ISSUE TITLE
Show the service banners of open ports

### ISSUE THREAD

**Issue by sniperle** [aaronjwood/PortAuthority#7]
How about reading service banners from connected sockets ?
Like:  SSH-2.0-OpenSSH_6.7

**Comment by aaronjwood** [comment]
Another good idea :) I'll probably have it so that you can click on a port which will pop up a little dialog showing this information with maybe a few other things...

**Comment by aaronjwood** [comment]
This has been implemented for SSH and HTTP(S) services and will be included in the next release.
