### ISSUE TITLE
 Port 53 (domain) scan (WAN) reports it as always open

### ISSUE THREAD

**Issue by Tony-il-Capo** [aaronjwood/PortAuthority#73]
Hi
Scanning my network for open ports via WAN always reports port 53 open. I'm pretty sure it's closed.
Checking with public domains also reports port 53 open for all of them. Testing with a non FOSS web service reports port 53 closed. 

Is it something wrong or am I missing something?

**Comment by aaronjwood** [comment]
Are you doing a WAN scan while being connected to your local network by any chance? Or are you on 3G/4G when doing this?

**Comment by Tony-il-Capo** [comment]
No, I'm not connected to local network (wifi), only to 3G.

But, I actually found what's causing this, I have a custom DNS rule on IPTABLES, I kinda forgot about it, basically every request for port 53 get redirected to the DNS server IP. As it is a DNS server, port 53 is (always) open as reported by Port Authority.

Sorry, my bad and thanks.

**Comment by aaronjwood** [comment]
No worries, glad you figured it out!
