### ISSUE TITLE
Allow for a user-specified Wake-on-LAN host

### ISSUE THREAD

**Issue by aaronjwood** [aaronjwood/PortAuthority#74]
ARP entries can time out if the host that's sleeping has been sleeping for a while, which means our host discovery will no longer pick it up. Need to allow users to input their own MAC address for whatever host they want to wake.

**Comment by mtbu** [comment]
What about a list of bookmarked hosts (store MAC address) for wake-on-lan?

**Comment by aaronjwood** [comment]
I was thinking of that as well. I could do something like store the discovered hosts in the local DB and display them whenever a user is back on the same network. Detection of the right network could use the BSSID, though that wouldn't work for #76. Then the host scan could just do a diff underneath to add new hosts or weed out old ones.

I'll probably split this into two separate features and tie them together for this WoL functionality.

**Comment by aaronjwood** [comment]
Should land in the next release! https://github.com/aaronjwood/PortAuthority/commit/497ce1b3ce6645ba964dbfd325398435bbc8f1fd
