### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by Tony-il-Capo** [aaronjwood/PortAuthority#75]
Hi
Being an open source app we can always dig through the code, but I think it would be wise to clarify whether or not Port Authority (including public IP discovering) collects and/or sends any data to third parties. 
Many privacy concerned users just don't have the skills to check this themselves.

A small sincere statement should be enough.

Thanks for your time.

**Comment by aaronjwood** [comment]
Thanks for the suggestion, do you think this existing blurb is sufficient https://github.com/aaronjwood/PortAuthority/blob/development/README.md#how-is-my-public-ip-discovered-im-worried-about-my-privacy or were you thinking of a separate document that states no data is collected?

**Comment by Tony-il-Capo** [comment]
That refers directly to public ip discovery, so aside that, the app could also collect and send more data (e.g. the domains, IP and ports we scan (user tracking))

Also, [in what you mentioned](https://github.com/aaronjwood/PortAuthority/blob/development/README.md#how-is-my-public-ip-discovered-im-worried-about-my-privacy), there's nothing about if private data is collected or not.

I think a separate document that covers the whole app is a better idea, **or** a specific section in the README.

It's all about being transparent and honest.

**Comment by aaronjwood** [comment]
https://github.com/aaronjwood/PortAuthority#privacy
