### ISSUE TITLE
Copperhead OS: 'Scanning For Hosts' reaches 100% then freezes indefinitely.

### ISSUE THREAD

**Issue by cycoh** [aaronjwood/PortAuthority#79]
Copperhead OS: 'Scanning For Hosts' reaches 100% then freezes indefinitely.
No results given.
OS: Copperhead OS (Angler) Nexus 6P.

Love this app but I cannot get it to work on this OS.

**Comment by aaronjwood** [comment]
Thanks for the feedback. Does this happen for you on any network you scan when using this OS? Also, how many hosts does it say there are in your subnet to scan?

**Comment by thestinger** [comment]
Can you check `dmesg` to see if there are SELinux denials? CopperheadOS doesn't permit third party apps to access most of `/proc/net`. Depending on what's needed, it might be reasonable to add another exception to the policy.

**Comment by aaronjwood** [comment]
Sounds like `/proc/net` access is the issue https://github.com/aaronjwood/PortAuthority/blob/cab9598fc884beb249eb40354e03c6b8d07a0594/app/src/main/java/com/aaronjwood/portauthority/async/ScanHostsAsyncTask.java#L91

**Comment by thestinger** [comment]
Yeah, that's it:

    07-20 00:52:33.154 11325 11325 W d.portauthority: type=1400 audit(0.0:602): avc: denied { read } for name="arp" dev="proc" ino=4026532379 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc_net:s0 tclass=file permissive=0

**Comment by aaronjwood** [comment]
@cycoh I guess I could add in a check to make sure `/proc/net/arp` is readable so that it doesn't hang forever, but you still won't be able to discover any hosts.

@thestinger is it expected that this SELinux violation won't propagate up to Dalvik (or the ART) and cause an exception or a hard crash?

**Comment by thestinger** [comment]
@aaronjwood SELinux violations report an access violation from the system call (EPERM usually) but it looks like you're ignoring `IOException` there.

In theory there could be a permission for accessing network information, so if I did that PortAuthority could add some `co.copperhead` namespaced permission.

The alternative is adding this to `proc_net_devroute` with the others that are allowed to be accessed from `untrusted_app`:

```
genfscon proc /net/dev u:object_r:proc_net_devroute:s0
genfscon proc /net/if_inet6 u:object_r:proc_net_devroute:s0
genfscon proc /net/ipv6_route u:object_r:proc_net_devroute:s0
genfscon proc /net/route u:object_r:proc_net_devroute:s0
```

Not sure if that makes sense based on why this was changed. It's not as bad as `/proc/net/tcp` but most apps have no business accessing it and in theory even stock Android is moving away from granting access to MAC addresses so a permission would make more sense.

**Comment by aaronjwood** [comment]
Ah, you're right. I forgot I don't bubble up those exceptions since a lot of stuff is contained within that `AsyncTask`. I need to add some extra code for these cases and bubble them up to some generic `AsyncResponse`.

Anyway, I'm open to adding a custom permission if that's the route you want to take. @cycoh I'm assuming you're willing to upgrade/patch in changes to the OS and this app to get things to work...?

**Comment by cycoh** [comment]
Hi aaronjwood and thestinger. I update everything as soon as it is available on CopperheadOS and FDroid. I am afraid I am not a programmer but just an end user so I hope I am making sense. I have tried using Port Authority on CopperheadOS on many different networks and I get the same issue. When I run Port Authority on my other phones that run LineageOS on the same networks the app works as expected.

**Comment by thanset** [comment]
@cycoh Good news, there is a fix.  It has to do with the way security works on CopperheadOS. Once the update is available I'm sure @aaronjwood or another maintainer will let you know when it's available on FDroid.

**Comment by thestinger** [comment]
The solution is likely adding a new feature to CopperheadOS, i.e. a permission to bypass the /proc/net rules. Unfortunately, it won't happen unless someone contributes it. I don't have time left for it.

**Comment by aaronjwood** [comment]
Closing this out as this is due to SELinux enforcement which will be a problem on any OS that uses it.
