### ISSUE TITLE
double items on list...

### ISSUE THREAD

**Issue by Bartoloni** [aaronjwood/PortAuthority#82]
sometimes the items on list are doubled (some IP Adress... and same MAC) .. here an image: http://www.wcn.it/port.jpg

this happens to me sometimes when i access for the first time a network... (after switching on main router)

.. yesterday the same thing happened but in avery very strange mode... same device with 2 different IP... smartphone of my wife discovered at 192.168.1.2 and 192.168.1.4 (same mac adsress).. after 2 "rescan" the second entry (1.4) disappeared.

BTW.. great APP!!

**Comment by aaronjwood** [comment]
Thanks for the feedback! This sounds very strange indeed. Can you tell me the device + OS version you're using? Also I see that your SSID is `Android ADB Bridge`. Is that a regular network of yours or are you doing some debugging via https://developer.android.com/studio/command-line/adb.html#wireless? Do have any special setup on your network like static ARP entries or anything like that?

Regarding the two different IPs scenario, are the addresses on your network handed out via DHCP? If so are the lease times very short? Maybe the lease expired at that time and the device got a new IP?

**Comment by aaronjwood** [comment]
Another thought, do you have multiple interfaces on this device? If so is it possible that more than one interface has the same IP + MAC in your case? The reason I ask is because the host discovery partially relies on reading the device's ARP table so if there are duplicate entries I'm wondering if it's because they are corresponding to other interfaces.

**Comment by Bartoloni** [comment]
very thank you for give time to my report :)

Hi, using your app compiled using latest Android Studio, on a Micromax Q450 ( android 5.1.1) ... the network i use is a standard network  (DSL modem with just the WIFI enabled) .. the name i give to network is just to make confusion on neighbors :p 
the doubled IPs.. are from an usual smartphone .. an old HTC Evo 3D (just made hard reset.. to make all settings standard) and the other one was my DSL modem (standard settings). seems that the bug happens when launching app.. pressing fast the "SCAN BUTTON" ... and after detection, press again the SCAN button.. but just some times....

**Comment by Bartoloni** [comment]
ssems that the doubled items appears after first "rendering"...  i press the scan button.. the scan finish.. the list is populated by 3 itesm (for example) .. after a while.. 1-3 seconds... other elements are added to list (with doubled IPs)

**Comment by aaronjwood** [comment]
Thanks for the info. I'll look more into this.

**Comment by Bartoloni** [comment]
you can reproduce the bug doing this:

on a netork of 5-6 hosts.. just click DISCOVER HOST.... and continue pressing the button ... after first discovery was completed... a new discovery starts . ( first list appears on background f discovery).. after second discovery.. the list has doubled elements...

this happens also when network is slow.. or the WIFI signal is poor... .. the list was not populated immediately.. and starting a new discovery .. double the items found.

**Comment by aaronjwood** [comment]
Thanks! I have an idea of what's causing this. I'll work on a fix that should be in the next version.

**Comment by Bartoloni** [comment]
nice nice!

**Comment by aaronjwood** [comment]
This should be addressed in the next update. If for some reason you find that you still see the issue definitely open this back up!
