### ISSUE TITLE
Mac Address database is from 2015

### ISSUE THREAD

**Issue by Bartoloni** [aaronjwood/PortAuthority#84]
now is very old, new apple/samsung device are not identified..
this is an updated one :) http://www.wcn.it/network.zip (2017)

**Comment by aaronjwood** [comment]
I had compiled the database about a year ago using data from the IEEE. Here's the commit https://github.com/aaronjwood/PortAuthority/commit/d796530e0ff7f844ee2b80bb6314371dbc89262e

I get your point though :) I think the real solution to this would be to do away with shipping the database along with the application and instead just build out the DB on upgrade of a new version and allow for automatic updates.

**Comment by Bartoloni** [comment]
sorry .. i was thinking it's from 2015 :( my fault.
yep.. automatically update can be best solution.. .. but also . MAC ADRESSES are growing very slowly... usually a company re-use owned addresses...
probably the DB can be updated every 4-6 months... and this can be made on sources, an automatic DB checkor a button to press for the check can do nothing for months... (i hate these types of buttons.. like the "firmware upgrade on android"... i press it every week.. for nothing.)

**Comment by aaronjwood** [comment]
No worries. I'll take a look at your zip file when I'm back from my business trip. At the least I can get an updated database in the next version while the automatic updating feature is in the works.

I was thinking of not even having a button. I could probably do some checks and determine if it needs to be updated at all without any user intervention. If it doesn't need an update the user should see nothing. If it does I could throw up some indicator showing the progress of the DB upgrade. Should be totally hands off for the user that way.

**Comment by aaronjwood** [comment]
Can you send a pull request for the updated db? That'll make it easier for me to quickly test it out.

**Comment by aaronjwood** [comment]
This is addressed by https://github.com/aaronjwood/PortAuthority/issues/45#issuecomment-346171580
