### ISSUE TITLE
Show retrieval date IEEE database

### ISSUE THREAD

**Issue by PanderMusubi** [aaronjwood/PortAuthority#86]
Please, show somewhere in the app the date and time of when the IEEE database that is being used was downloaded.

**Comment by aaronjwood** [comment]
Do you still think this would be useful if the user is now able to update the database themselves whenever they want? I've merged in lots of code recently that will download the IEEE + IANA data on a fresh install, and will allow the user to update the OUI and/or port data whenever they want.

**Comment by PanderMusubi** [comment]
Haven't tested the latest version yet. Will let you know.

**Comment by aaronjwood** [comment]
I think that with the new version that's now rolled out there won't be much need for this since the database can be updated at any point by the user. If you disagree feel free to reopen this and we can discuss more.
