### ISSUE TITLE
Offer link to provide feedback to IEEE

### ISSUE THREAD

**Issue by PanderMusubi** [aaronjwood/PortAuthority#87]
Instead of adding fixes to the database, provide alao a link in the app to https://regauth.standards.ieee.org/standards-ra-web/pub/view.html#registries or something more suitable for users to check unsupported devices or devices with errors in their name.

Please, also send all custom corrections which are now amede in the app to IEEE via the feedback link above to get fixed.

**Comment by aaronjwood** [comment]
Related to IEEE feedback: https://github.com/aaronjwood/PortAuthority/issues/45#issuecomment-344368551

**Comment by aaronjwood** [comment]
I now wonder how open they'd be to feedback... https://github.com/aaronjwood/PortAuthority/issues/45#issuecomment-344659846

**Comment by aaronjwood** [comment]
I think we can probably close this out now as the data can be downloaded on demand from IEEE and/or IANA. Let me know if you feel that this is still necessary.
