### ISSUE TITLE
too many added ports to the arrayee

### ISSUE THREAD

**Issue by Bartoloni** [aaronjwood/PortAuthority#88]
it's right to add to the array/list all ports that return a timeout error?
i tried to reduce time to 100 millisecs and on some networks half ports return me an timeout (toast) error, NOT RESPONDING... but watching at the final list.. all these ports are listed.

**Comment by aaronjwood** [comment]
No, that doesn't sound right. Are you running into this issue with the current production version?

**Comment by aaronjwood** [comment]
Where are you seeing a toast pop up for timeout errors? Is this some change that your testing out on your own fork? I don't send a toast for every socket timeout for obvious reasons.

**Comment by Bartoloni** [comment]
i used laetst sourecs from GitHuB (here) compiled , launched.. and there are TOAST messages ( errors.java on utils )
here a screenshot : http://www.wcn.it/toast.png

for example after this scan on a standard PC (ethernet cable) .. on the resulting list of ports... the port 8 appears (and also all the 1024 ports) .. the port has the text "Unknown" on the side.

**Comment by aaronjwood** [comment]
Oh, you're on the development branch here. Things are currently in progress and constantly changing on the development branch so I wouldn't use it for any kind of "real" release. So the behavior you're seeing is not correct but expected if you're using the development branch.

**Comment by Bartoloni** [comment]
i see the recent changes on the timeout catch..
app/src/main/java/com/aaronjwood/portauthority/runnable/ScanPortsRunnable.java
this fixes the issue.

**Comment by aaronjwood** [comment]
Yup, just something left over from when I was last working on it that I hadn't gotten around to changing. If you see these kinds of issues in the future feel free to send a PR! You can always assume `development` to be unstable but also a place to branch from for PRs.
