### ISSUE TITLE
Unnecessary code?

### ISSUE THREAD

**Issue by goodandrewsoft** [aaronjwood/PortAuthority#90]
This question does not try to compromise you, but is only educational for personal purposes.

I've modified your [method](https://github.com/aaronjwood/PortAuthority/blob/bca2f030199795cd9549f86b9848de183497bc5d/app/src/main/java/com/aaronjwood/portauthority/network/Wireless.java#L120) a little: 

My debugger:
![image](https://user-images.githubusercontent.com/2471892/33711998-91587182-db4e-11e7-8c98-8c8889c2d26e.png)

Is it this code
```java
...
byte[] ipByteArray = BigInteger.valueOf(ip).toByteArray();
final int value = new BigInteger(InetAddress.getByAddress(ipByteArray).getAddress()).intValue();
...
```

is necessery? If **yes**, why?

**Comment by aaronjwood** [comment]
The reason why that method uses generics is because I wanted to save some code/duplication and be able to call it different ways. See https://github.com/aaronjwood/PortAuthority/blob/bca2f030199795cd9549f86b9848de183497bc5d/app/src/main/java/com/aaronjwood/portauthority/network/Wireless.java#L76 and https://github.com/aaronjwood/PortAuthority/blob/bca2f030199795cd9549f86b9848de183497bc5d/app/src/main/java/com/aaronjwood/portauthority/activity/MainActivity.java#L257

I'm using BigInteger there as an easy way to get a byte array since `InetAddress.getByAddress` takes in a byte array. This is probably not optimal and a `ByteBuffer` might have been a better fit here.

**Comment by goodandrewsoft** [comment]
My question not about generic:

I'm mean, if your method returns int, then:
`ip = Integer.reverseBytes(ip);` = 
            `new BigInteger(InetAddress.getByAddress(BigInteger.valueOf(ip).toByteArray()).getAddress()).intValue())`

So, you can return just `type.cast(ip)`;  I'm right?

**Comment by aaronjwood** [comment]
The method returns either an Integer or a String which is why I mentioned the generics. If it returned a single type then I wouldn't need to cast anything.

**Comment by goodandrewsoft** [comment]
https://user-images.githubusercontent.com/2471892/33711998-91587182-db4e-11e7-8c98-8c8889c2d26e.png
 IP and Value is the SAME? YOU really not understand?

**Comment by aaronjwood** [comment]
Are you asking about your code for something unrelated or about the method that's currently being used in this project?

If you're asking about your code then it's orthogonal as you're doing something completely different that won't work for how I'm using that method. If you're asking about the method that's currently in place then to answer what you said above `I'm mean, if your method returns int, then:` no the method is not just returning an int.

**Comment by goodandrewsoft** [comment]
You can modify your method like this:
```java

public <T> T getInternalWifiIpAddress(Class<T> type) throws UnknownHostException, NoWifiManagerException {
        int ip = getWifiInfo().getIpAddress();

        //Endianness can be a potential issue on some hardware
        if (ByteOrder.nativeOrder().equals(ByteOrder.LITTLE_ENDIAN)) {
            ip = Integer.reverseBytes(ip);
        }

  if (type.isInstance("")) {
            return type.cast(InetAddress.getByAddress(BigInteger.valueOf(ip).toByteArray()).getHostAddress());
        } else {
            return type.cast(ip);
        }

    }
```

**Comment by aaronjwood** [comment]
I see, I misunderstood your question. You're right that I can get rid of the `BigInteger` usage inside of the `else` block.

**Comment by goodandrewsoft** [comment]
Finally :)

**Comment by aaronjwood** [comment]
Adding this for documentation purposes: Google doesn't document the `getIpAddress` method https://developer.android.com/reference/android/net/wifi/WifiInfo.html#getIpAddress()

For anyone coming across this in the future, it's safe to say that the internals of `getIpAddress` return the same output as doing the conversion yourself.

**Comment by goodandrewsoft** [comment]
So? My code not dangerous?
