### ISSUE TITLE
GPLv3 Violation

### ISSUE THREAD

**Issue by VREMSoftwareDevelopment** [aaronjwood/PortAuthority#91]
Hi @aaronjwood 

We found [this app on the Google Play Store](https://play.google.com/store/apps/details?id=com.baniapptech.whousemywifi). 

Their application looks suspiciously like your application with some minor changes.

Link to report alleged copyright infringement to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay).

**Comment by aaronjwood** [comment]
Wow, thanks for the heads up on this. I'll look into it.

**Comment by aaronjwood** [comment]
Yeah....this must be mine because the second screenshot contains my words exactly https://lh3.googleusercontent.com/ECxhAkExkzwWji9VLERmQyKyX2ZBWd0jMPF9MIave0W1HBAnpoW0O_Ir6o1jFojJAcoi=h900-rw

**Comment by VREMSoftwareDevelopment** [comment]
They have copied our application as well. 
Google removed the copy of our application today.

**Comment by aaronjwood** [comment]
Sorry to hear that but glad you were able to get it resolved! Thanks again for letting me know about this. I really appreciate it!

**Comment by VREMSoftwareDevelopment** [comment]
@aaronjwood If you need any help on this, send us an email VREMSoftwareDevelopment@gmail.com

**Comment by aaronjwood** [comment]
Adding this one for reference https://play.google.com/store/apps/details?id=com.appworld.whousemywifi

**Comment by timofonic** [comment]
@aaronjwood Any news about this? Why hasn't this plagiarism and GPLv3 violation been removed?
